<!--
    pageCount
    previous
    first
    next
    last
-->

<?php if($this->current != 1): ?>
<a href="<?= $this->url(array('page' => $this->first)) ?>">Prima pagina </a>
<?php endif; ?>

<?php if($this->current != $this->first): ?>
<a href="<?= $this->url(array('page' => $this->previous)) ?>">&lt;&lt; Pagina precedente</a>
<?php endif; ?>

 Pagina <?= $this->current ?> / <?= $this->pageCount ?>

<?php if($this->current != $this->last): ?>
<a href="<?= $this->url(array('page' => $this->next)) ?>"> Pagina successiva &gt;&gt;</a>
<?php endif; ?>

<?php if($this->current != $this->last): ?>
<a href="<?= $this->url(array('page' => $this->last)) ?>"> Ultima pagina</a>
<?php endif; ?>