<!--
    pageCount
    previous
    first
    next
    last
-->

<?php $params = '/?'.$this->params ?>

<?php if($this->current != 1): ?>
<a href="<?= $this->url(array('page' => $this->first), null, false).$params ?>">Prima pagina </a>
<?php endif; ?>

<?php if($this->current != $this->first): ?>
<a href="<?= $this->url(array('page' => $this->previous), null, false).$params ?>">&lt;&lt; Pagina precedente</a>
<?php endif; ?>

 Pagina <?= $this->current ?> / <?= $this->pageCount ?>

<?php if($this->current != $this->last): ?>
<a href="<?= $this->url(array('page' => $this->next), null, false).$params ?>"> Pagina successiva &gt;&gt;</a>
<?php endif; ?>

<?php if($this->current != $this->last): ?>
<a href="<?= $this->url(array('page' => $this->last), null, false).$params ?>"> Ultima pagina</a>
<?php endif; ?>
