<div class="page">
    <div class="container page-content">

        <h1 class="page-heading">Locali</h1>
        <a class="button button-selected" href="
            <?= $this->url(array(
            'controller' => 'accomodation',
            'action' => 'add'
        ), 'default', true); ?>
        ">Nuovo annuncio</a>

        <div class="grid">

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Titolo</th>
                        <th>Data inserimento</th>
                        <th>Indirizzo</th>
                        <th>Numero interessati</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($this->data as $d): ?>
                    <tr>
                        <td><?= $d['accomodation']->title; ?></td>
                        <td><?= $d['accomodation']->created; ?></td>
                        <td><?= $d['accomodation']->address; ?></td>
                        <td><?= count($d['options']); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

        </div>
    </div>
</div>