<div class="grid">
    <div class="sidebar">

        <div class="sidebar-menu">

            <div class="grid grid-pad">

                <div class="col-1-1">

                    

                </div>

            </div>

        </div>

    </div>
    <div class="content grid">

        <div class="col-1-4">
            <div class="panel">
                <div class="panel-image">
                    <img src="http://placehold.it/400x200" alt=""/>
                </div>
                <div class="panel-heading">
                    <h2 class="panel-title">Na bella villozza <span class="float-right prezzo">300$ / mese</span></h2>
                </div>
                <div class="panel-body grid">
                    <div class="col-1-2">
                        <ul class="list-unstyled">
                            <li><b>Tipologia:</b> <span>Villozza</span></li>
                            <li><b>Dimensione:</b> <span>2000 m&sup2;</span></li>
                        </ul>
                    </div>
                    <div class="col-1-2">
                        <ul class="list-unstyled">
                            <li><b>Locatario:</b> <span>Mario Fonzi</span></li>
                            <li><b>Periodo:</b> <span> 1 anno</span></li>
                        </ul>
                    </div>
                    <div class="col-1-1 text-justified">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat...
                    </div>
                    <div class="col-1-1 text-center">
                        <a class="button button-primary" href="#">Dettagli</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-1-4">
            <div class="panel">
                <div class="panel-image">
                    <img src="http://placehold.it/400x200" alt=""/>
                </div>
                <div class="panel-heading">
                    <h2 class="panel-title">Na bella villozza <span class="float-right prezzo">300$ / mese</span></h2>
                </div>
                <div class="panel-body grid">
                    <div class="col-1-2">
                        <ul class="list-unstyled">
                            <li><b>Tipologia:</b> <span>Villozza</span></li>
                            <li><b>Dimensione:</b> <span>2000 m&sup2;</span></li>
                        </ul>
                    </div>
                    <div class="col-1-2">
                        <ul class="list-unstyled">
                            <li><b>Locatario:</b> <span>Mario Fonzi</span></li>
                            <li><b>Periodo:</b> <span> 1 anno</span></li>
                        </ul>
                    </div>
                    <div class="col-1-1 text-justified">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat...
                    </div>
                    <div class="col-1-1 text-center">
                        <a class="button button-primary" href="#">Dettagli</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-1-4">
            <div class="panel">
                <div class="panel-image">
                    <img src="http://placehold.it/400x200" alt=""/>
                </div>
                <div class="panel-heading">
                    <h2 class="panel-title">Na bella villozza <span class="float-right prezzo">300$ / mese</span></h2>
                </div>
                <div class="panel-body grid">
                    <div class="col-1-2">
                        <ul class="list-unstyled">
                            <li><b>Tipologia:</b> <span>Villozza</span></li>
                            <li><b>Dimensione:</b> <span>2000 m&sup2;</span></li>
                        </ul>
                    </div>
                    <div class="col-1-2">
                        <ul class="list-unstyled">
                            <li><b>Locatario:</b> <span>Mario Fonzi</span></li>
                            <li><b>Periodo:</b> <span> 1 anno</span></li>
                        </ul>
                    </div>
                    <div class="col-1-1 text-justified">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat...
                    </div>
                    <div class="col-1-1 text-center">
                        <a class="button button-primary" href="#">Dettagli</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-1-4">
            <div class="panel">
                <div class="panel-image">
                    <img src="http://placehold.it/400x200" alt=""/>
                </div>
                <div class="panel-heading">
                    <h2 class="panel-title">Na bella villozza <span class="float-right prezzo">300$ / mese</span></h2>
                </div>
                <div class="panel-body grid">
                    <div class="col-1-2">
                        <ul class="list-unstyled">
                            <li><b>Tipologia:</b> <span>Villozza</span></li>
                            <li><b>Dimensione:</b> <span>2000 m&sup2;</span></li>
                        </ul>
                    </div>
                    <div class="col-1-2">
                        <ul class="list-unstyled">
                            <li><b>Locatario:</b> <span>Mario Fonzi</span></li>
                            <li><b>Periodo:</b> <span> 1 anno</span></li>
                        </ul>
                    </div>
                    <div class="col-1-1 text-justified">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat...
                    </div>
                    <div class="col-1-1 text-center">
                        <a class="button button-primary" href="#">Dettagli</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>