<div class="page">
    <div class="container page-content">

        <h1 class="page-heading">Locali</h1>

        <div class="grid">

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td></td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>