<div class="page">
    <div class="container page-content">

        <h1 class="page-heading">Annunci</h1>

        <div class="grid">
            <div class="col-1-1">
                <p class="alert alert-info">Da questa pagina è possibile creare nuovi annunci manualmente, oppure aggiornare o cancellare quelli esistenti.</p>
            </div>
        </div>

        <div class="grid">

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Titolo</th>
                        <th>Zona</th>
                        <th>Locatario</th>
                        <th>Periodo Disp.</th>
                        <th>Canone</th>
                        <th>Azioni</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->allAccomodations as $a): ?>
                        <tr>
                            <td><a href="
                            <?= $this->url(array(
                                    'controller' => 'accomodation',
                                    'action' => 'get',
                                    'id' => $a->id
                                ), 'default', true) ?>"><?php echo $a->title;?></a></td>
                            <td><?php echo $a->zone;?></td>
                            <td><?php echo $a->lesser;?></td>
                            <td><?php echo $a->available_from . ' - ' . $a->available_untill;?></td>
                            <td><?php echo $a->fee;?></td>
                            <td>
                                <a class="button" href="
                                <?= $this->url(array(
                                    'controller' => 'accomodation',
                                    'action' => 'edit',
                                    'accomodation' => $a->id
                                ), 'default', true) ?>">Modifica</a>
                                <a class="button button-danger" href="<?= $this->url(array(
                                    'controller' => 'accomodation',
                                    'action' => 'delete',
                                    'id' => $a->id
                                ), 'default', true) ?>">Cancella</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

        </div>
    </div>
</div>