<div class="page">
    <div class="container page-content">

        <h1 class="page-heading float-left">Impostazioni</h1>

        <?php if(null == $this->faq): ?>
        <h1 class="page-heading"><?= $this->message; ?><a class="button button-danger float-right" href="<?= $this->url(
                array(
                    'controller' => 'loco',
                    'action' => 'faq-edit'
                ), 'default', true
            ); ?>">Annulla</a></h1>
        <?php endif; ?>

        <a class=" button float-right" href="
            <?= $this->url(array(
            'controller' => 'loco',
            'action' => 'faq-add'
        ), 'default', true);
            ?>
        ">Aggiungi</a>

        <div class="grid">
            <?php
                if(isset($this->form)) echo $this->form;
            ?>
            <?php if(!isset($this->form)): ?>
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Domanda</th>
                        <th>Risposta</th>
                        <th>Azioni</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($this->faq as $f): ?>
                        <tr>
                            <td><?= $f->id ?></td>
                            <td><?= $f->question ?></td>
                            <td><?= $f->answer ?></td>
                            <td>
                                <a class="button" href="<?= $this->url(array(
                                    'controller' => 'loco',
                                    'action' => 'faq-edit',
                                    'id' => $f->id
                                ), 'default', true); ?>">Edita</a>
                                <a class="button button-danger" href="
                                    <?= $this->url(array(
                                    'controller' => 'loco',
                                    'action' => 'faq-delete',
                                    'id' => $f->id
                                ), 'default', true); ?>
                                ">Cancella</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>

        </div>
    </div>
</div>