<div class="splash">
    <div class="container text-center">
        <h1>Trova o affitta il locale perfetto!</h1>        
    </div>
</div>
<div class="cta">
    <div class="container text-center">
        <div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, omnis, deleniti tempore ea iste aut id eius laborum iusto beatae ex excepturi fuga delectus dolor sit magni magnam voluptas natus.</p>
        </div>
    </div>
</div>
<div class="page">
    <div class="container">//features</div>
</div>