<div class="splash">
    <div class="container text-center">
        <h1>Trova o affitta il locale perfetto!</h1>        
    </div>
</div>
<div class="cta">
    <div class="container grid">
        <div class="col-1-2">
            <h3>Vuoi affittare una casa o un appartamento a studenti? </h3>
            <p>
                Loco è la soluzione migliore. Non dovrai più stampare e appendere centinaia di volantini per tutta la città. Il nostro servizio è semplice ed intuitivo e ti metterà in contatto con tutti i locatari interessati. Basta mettere il tuo annuncio su Loco!
            </p>
            <p class="text-center"><a class="button button-primary" href="<?= $this->url(array(
                    'controller' => 'user',
                    'action' => 'register'
                ), 'default', true); ?>">Diventa un locatore</a></p>
        </div>
        <div class="col-1-2">
            <h3>Sei uno studente in cerca di un alloggio? </h3>
            <p>
                Questo è il posto migliore per trovarla. Loco ti offre centinaia di annunici, in grado di soddisfare ogni tua richiesta. Inoltre il nostro servizio ti consente di vedere e contattare il Locatore con un semplice click, senza dover girare tutta la città!
            </p>
            <p class="text-center"><a class="button button-primary" href="<?= $this->url(array(
                    'controller' => 'user',
                    'action' => 'register'
                ), 'default', true); ?>">Registrati e via!</a></p>
        </div>
    </div>
</div>
<div class="page features">
    <div class="container page-content">

        <h1 class="page-heading text-center"><a href="https://docs.google.com/document/d/1Pkit2UkiT-ayUBp3-q_JBaJFBqIl8gDwdjoFKtq0LyE/edit?usp=sharing" title="relazione">Leggi la relazione</a></h1>
        <p class="text-center">-oppure-</p>
        <h1 class="page-heading text-center">Scopri tutti i vantaggi di LOCO</h1>

        <div class="grid ">

            <div class="col-5-12">
                <img src="<?= $this->baseUrl('img/features/loco1.jpg') ?>" alt="Locatari: Trova la casa dei tuoi sogni"/>
            </div>
            <div class="col-7-12">
                <h3>Locatari: Trova la casa dei tuoi sogni</h3>
                <p>Lorem Ipsum</p>
            </div>

        </div>
        <div class="grid text-right">
            <div class="col-7-12">
                <h3>Messaggistica integrata</h3>
                <p>Lorem Ipsum</p>
            </div>
            <div class="col-5-12">
                <img src="<?= $this->baseUrl('img/features/loco2.jpg') ?>" alt="Messaggistica integrata"/>
            </div>
        </div>
        <div class="grid ">

            <div class="col-5-12">
                <img src="<?= $this->baseUrl('img/features/loco3.jpg') ?>" alt="Locatari: Tutti i dettagli che ti servono"/>
            </div>
            <div class="col-7-12">
                <h3>Locatari: Tutti i dettagli che ti servono</h3>
                <p>Lorem Ipsum</p>
            </div>

        </div>
        <div class="grid text-right">
            <div class="col-7-12">
                <h3>Locatori: Vedi subito lo stato dei tuoi annunci</h3>
                <p>Lorem Ipsum</p>
            </div>
            <div class="col-5-12">
                <img src="<?= $this->baseUrl('img/features/loco4.jpg') ?>" alt="Locatori: Vedi subito lo stato dei tuoi annunci"/>
            </div>
        </div>
        <hr/>
        <div class="grid text-center">
            <h3>Cosa aspetti?</h3>
            <a class="button button-primary" href="<?= $this->url(array(
                'controller' => 'user',
                'action' => 'register'
            ), 'default', true); ?>">Registrati subito!</a>
        </div>
    </div>
</div>