<div class="page">

    <div class="container page-content">
        <div class="alert alert-error">
            <h2>Errore!</h2>
            <p>Azione non autirizzata!</p>
        </div>
        <div class="text-center">
            <h2>
                <button class="button button-primary button-goback">
                    Torna indietro
                </button>
            </h2>
        </div>
    </div>
</div>