<div class="footer">
    <div class="container">
        <div class="grid">
            <div class="col-1-3">
                <h1 class="logo"><a href="#">Loco</a></h1>
                <p>Copyright 2014 Loco SRL</p>
            </div>
            <div class="col-1-3">
                <b>Recapiti</b>
                <ul class="list-unstyled">
                    <li>Loco SRL</li>
                    <li>Via dei Startup 55, 60121 Ancona</li>
                    <li>Italy</li>
                    <li>P.Iva: 1234567891263</li>
                    <li>Tel: +39 071 123456789 </li>
                    <li>Emai: admin@loco.it </li>
                </ul>
            </div>
            <div class="col-1-3">
                <b>Missione</b>
                <p>Loco - La soluzione all-in-one per affiti studenteschi - per business e individuale, per studente e uomo d'affari. La nostra misisone è offrire ad entrambi i mondi un ponte per incontrarsi e ritrovare quel che è umano in noi.</p>
            </div>
        </div>
    </div>
</div>