<!-- layout used for logged-in users -->

<?= $this->doctype() ?>
<html>
<head>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headTitle() ?>
</head>
<body>

    <div class="menu">
        <div class="container">
            <h1 class="logo float-left"><a href="#">Loco</a></h1>

            <ul class="list-inline float-right">
                <li>
                    <b>Ciao, <?= $this->whoIs()->name; ?>!</b>
                </li>
                <li>
                    <a href="<?= $this->url(
                        array(
                        'controller' => 'user',
                        'action' => 'logout'
                        ), 'default', true
                    ); ?>" class="button button-primary">Logout</a>
                </li>
            </ul>        
        </div>
    </div>

    <div class="submenu">
        <div class="container">
            <ul class="list-inline">
                <li class="active"><a href="#">Uno</a></li>
                <li><a href="#">Due </a></li>
                <li><a href="#">Tre <span class="badge badge-active">42</span> </a></li>
            </ul>      
        </div>
    </div>

    <!-- All that the view has produces will go here -->
    <?= $this->layout()->content ?>
    
    <div class="footer">
        <div class="container">
            <div class="grid">
                <div class="col-1-3">
                    <h1 class="logo"><a href="#">Loco</a></h1>
                    <p>Copyright 2014 Loco SRL</p>    
                </div>
                <div class="col-1-3">
                    <b>Site Map</b>
                    <ul class="list-unstyled">
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                    </ul>
                </div>
                <div class="col-1-3">
                    <b>Altra roba</b>
                    <ul class="list-unstyled">
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</body>
</html>
