<!-- layout used for logged-in users -->

<?= $this->doctype() ?>
<html>
<head>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headTitle() ?>
</head>
<body>

    <div class="menu">
        <div class="container">
            <h1 class="logo float-left"><a href="#">Loco</a></h1>
            <ul class="list-inline float-right">
                <li><img src="data:image/jpeg;base64,<?php echo base64_encode($this->whoIs()->profile_image); ?>" class="profile profilo_top" /></li>
                <li>
                    <b>Ciao, <?= $this->whoIs()->name; ?></b><a href="<?= $this->url(
                        array(
                            'controller' => 'user',
                            'action' => 'profile-view'
                        ), 'default', true
                    ); ?>"> (Profilo)</a>
                </li>
                <li>
                    <a href="<?= $this->url(
                        array(
                        'controller' => 'user',
                        'action' => 'logout'
                        ), 'default', true
                    ); ?>" class="button button-primary">Logout</a>
                </li>
            </ul>        
        </div>
    </div>

    <div class="submenu">
        <div class="container">
            <ul class="list-inline">
                <?php if($this->whoIs()->role == 'lesser'): ?>
                    <li class="<?php $this->activeLink('accomodation', 'index');?>"><a href="<?= $this->url(array('controller' => 'accomodation', 'action' => 'index'), 'default', true); ?>">I tuoi Annunci</a></li>
                    <li class="<?php $this->activeLink('contract', 'index');?>"><a href="<?= $this->url(array('controller' => 'contract', 'action' => 'index'), 'default', true); ?>">I tuoi contratti </a></li>
                <?php elseif($this->whoIs()->role == 'lessee'): ?>
                    <li class="<?php $this->activeLink('accomodation', 'search');?>"><a href="<?= $this->url(array('controller' => 'accomodation', 'action' => 'search'), 'default', true); ?>">Cerca Annunci</a></li>
                    <li class="<?php $this->activeLink('contract', 'index');?>"><a href="<?= $this->url(array('controller' => 'contract', 'action' => 'index'), 'default', true); ?>">I tuoi Annunci </a></li>
                <?php elseif($this->whoIs()->role == 'admin'): ?>
                    <li class="<?php $this->activeLink('loco', 'statistics');?>"><a href="<?= $this->url(array('controller' => 'loco', 'action' => 'statistics'), 'default', true); ?>">Statistiche</a></li>
                    <li class="<?php $this->activeLink('user', 'view-all');?>"><a href="<?= $this->url(array('controller' => 'user', 'action' => 'view-all'), 'default', true); ?>">Utenti</a></li>
                    <li class="<?php $this->activeLink('accomodation', 'view-all');?>"><a href="<?= $this->url(array('controller' => 'accomodation', 'action' => 'view-all'), 'default', true); ?>">Annunci</a></li>
                    <li class="<?php $this->activeLink('loco', 'faq-edit');?>"><a href="<?= $this->url(array('controller' => 'loco', 'action' => 'faq-edit'), 'default', true); ?>">Impostazioni</a></li>
                <?php endif; ?>
                    <li class="<?php $this->activeLink('message', 'list');?>"><a href="<?= $this->url(array('controller' => 'message', 'action' => 'list'), 'default', true); ?>">Messaggi </a></li>
            </ul>
        </div>
    </div>

    <!-- All that the view has produces will go here -->
    <?= $this->layout()->content ?>
    
    <div class="footer">
        <div class="container">
            <div class="grid">
                <div class="col-1-3">
                    <h1 class="logo"><a href="#">Loco</a></h1>
                    <p>Copyright 2014 Loco SRL</p>    
                </div>
                <div class="col-1-3">
                    <b>Site Map</b>
                    <ul class="list-unstyled">
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                    </ul>
                </div>
                <div class="col-1-3">
                    <b>Altra roba</b>
                    <ul class="list-unstyled">
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</body>
</html>
