<!-- Layout used for non logged-in users -->

<?= $this->doctype() ?>
<html>
<head>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headTitle() ?>
    <meta name="path" value="<?= Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>/<?= Zend_Controller_Front::getInstance()->getRequest()->getActionName(); ?>"/>
    <meta name="base" value="<?= $this->baseUrl(); ?>"/>
</head>
<body>

    <div class="menu">
        <div class="container">
            <h1 class="logo float-left">
                <a href="<?= $this->url(array(
                    'controller' => 'loco',
                    'action' => 'index'
                ), 'default', true); ?>">Loco</a>
            </h1>

            <ul class="list-inline float-right">
                <li class="<?php $this->activeLink('loco', 'index');?>">
                    <a class="link" href="<?= $this->url(array(
                        'controller' => 'loco',
                        'action' => 'index'
                    ), 'default', true); ?>">Home</a>
                </li>
                <li class="<?php $this->activeLink('loco', 'faq-view');?>">
                    <a class="link" href="<?= $this->url(array(
                        'controller' => 'loco',
                        'action' => 'faq-view'
                    ), 'default', true); ?>">FAQ</a>
                </li>
                <li class="<?php $this->activeLink('loco', 'support-view');?>">
                    <a class="link" href="<?= $this->url(array(
                        'controller' => 'loco',
                        'action' => 'support-view'
                    ), 'default', true); ?>">Supporto</a>
                </li>
                <li>
                    <a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action' => 'register'
                    ), 'default', true); ?>" class="button button-primary">Registra</a>
                </li>                    
                <li>
                    <a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action' => 'login'
                    ), 'default', true); ?>" class="button">Log In</a>
                </li>
            </ul>        
        </div>
    </div>

    <!-- All that the view has produces will go here -->
    <?= $this->layout()->content ?>

    <div class="footer">
        <div class="container">
            <div class="grid">
                <div class="col-1-3">
                    <h1 class="logo"><a href="#">Loco</a></h1>
                    <p>Copyright 2014 Loco SRL</p>    
                </div>
                <div class="col-1-3">
                    <b>Site Map</b>
                    <ul class="list-unstyled">
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                    </ul>
                </div>
                <div class="col-1-3">
                    <b>Altra roba</b>
                    <ul class="list-unstyled">
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <?= $this->headScript() ?>

</body>
</html>