<!-- Layout used for non logged-in users -->

<?= $this->doctype() ?>
<html>

<?= $this->render('header.phtml'); ?>

<body>
    <!--<div id="loader">Loading</div>-->
    <div class="menu">
        <div class="container">
            <h1 class="logo float-left">
                <a href="<?= $this->url(array(
                    'controller' => 'loco',
                    'action' => 'index'
                ), 'default', true); ?>">Loco</a>
            </h1>

            <ul class="list-inline float-right">
                <li class="<?php $this->activeLink('loco', 'index');?>">
                    <a class="link" href="<?= $this->url(array(
                        'controller' => 'loco',
                        'action' => 'index'
                    ), 'default', true); ?>">Home</a>
                </li>
                <li class="<?php $this->activeLink('loco', 'faq-view');?>">
                    <a class="link" href="<?= $this->url(array(
                        'controller' => 'loco',
                        'action' => 'faq-view'
                    ), 'default', true); ?>">FAQ</a>
                </li>
                <li class="<?php $this->activeLink('loco', 'tos-view');?>">
                    <a class="link" href="<?= $this->url(array(
                        'controller' => 'loco',
                        'action' => 'tos-view'
                    ), 'default', true); ?>">Termini d'utilizzo</a>
                </li>
                <li>
                    <a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action' => 'register'
                    ), 'default', true); ?>" class="button button-primary">Registra</a>
                </li>                    
                <li>
                    <a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action' => 'login'
                    ), 'default', true); ?>" class="button">Log In</a>
                </li>
            </ul>        
        </div>
    </div>

    <!-- All that the view has produces will go here -->
    <?= $this->layout()->content ?>

    <?= $this->render('footer.phtml'); ?>

    <?= $this->headScript() ?>

</body>
</html>