<div class="page login">
    <div class="container grid">
        <div class="col-2-3">&nbsp;</div>
        <div class="col-1-3">
            <div class="page-content">
                <h1 class="page-heading">Per favore, esegua il login</h1>
                <h4 class="login_error"><?= $this->message; ?></h4>
                <?php echo $this->loginForm; ?>
            </div>
        </div>
    </div>
</div>
