<div class="page">
    <div class="container page-content">

        <h1 class="page-heading">
            <a class="button button-danger float-right button-goback" href="#">Annulla</a>
            <?= $this->message; ?>
        </h1>

        <div class="grid">
            <div class="col-1-4">
                <img class="float-left profile-big" src="data:image/jpeg;base64,<?php echo base64_encode($this->profile_info->profile_image); ?>" />
            </div>
            <div class="col-3-4">
                <?= $this->form; ?>
            </div>

        </div>
    </div>
</div>