<div class="container messages">
    <div class="sidebar">

        <h2>Messaggi</h2>

        <div class="sidebar-menu">

            <ul class="list-inline messages-list">

                <?php foreach($this->data as $i): ?>
                    <li <?php if($this->selectedInterlocutor == $i['username']) echo 'class="active"'; ?>>
                        <a href="<?= $this->url(
                            array(
                                'controller' => 'message',
                                'action' => 'list',
                                'interlocutor' => $i['username']
                            )
                        ); ?>">
                            <img src="data:image/jpeg;base64,<?php echo base64_encode($i['profile_image']); ?>" class="float-left profile" alt=""/>
                            <b><?= $i['username']; ?></b>
                        </a>
                    </li>
                <?php endforeach; ?>

            </ul>

        </div>

    </div>
    <div class="content grid">

        <div class="messages-content" data-timestamp="<?= end($this->messages)['timestamp']; ?>" data-int1="<?= end($this->messages)['author']; ?>" data-int2="<?= end($this->messages)['recipient']; ?>">

            <?php foreach($this->messages as $m): ?>
                <div class="message grid">
                    <div class="col-3-12">
                        <img src="data:image/jpeg;base64,<?php echo base64_encode($m['author_profile_image']); ?>" class="float-left profile" alt=""/>
                        <b><?= $m['author']; ?></b>
                        <p><?= $m['timestamp']; ?></p>
                    </div>
                    <div class="col-9-12">
                        <p><?= $m['content']; ?></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="messages-input grid form text-center">
            <?= $this->form; ?>
        </div>

    </div>
</div>